alias cl="clear"
alias e-fish="vim ~/.config/fish/config.fish"
alias e-aliases="vim ~/.bash_aliases"
alias source-aliases="source ~/.bash_aliases"
alias apt-update="sudo apt update"
alias apt-upgrade="sudo apt upgrade"
alias gcloud-creds-export="export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json"
